spring:
  application:
  name: Webflux Course
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER}:${DB_PASSWORD}@cluster0.oftsr3e.mongodb.net/${DB_NAME}?retryWrites=true&w=majority&appName=Cluster0